name: Check users

on: push

jobs: 
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
      - name: Get users
        run: curl http://localhost:3001/api/users
