name: Check users

on: push

jobs: 
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: giltayar/myblog
        ports:
          - 3000:3000
      mongo:
        image: giltayar/mymongo
        ports:
          - 27017:27017
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
      - name: Get users
        run: curl http://localhost:3000
